tutorial limerick {

    verb topclimb [0]
    verb largeclimb [1]
    verb mediumclimb [2]
    verb normalclimb [3]
    verb push [4]
    verb crawl [5]
    verb eat [6]
    verb eat2 [7]
    verb cancel [8]
    verb snakefall [9]
        
    lesson 1: Lesson {
        learn to normalclimb     
    }

    lesson 2: Lesson {
        learn to normalclimb     
    }

    lesson 3: Lesson {
        learn to normalclimb     
    }

    lesson 4: Lesson {
        learn to mediumclimb    
    }
    
    lesson 5: Lesson {
        learn to mediumclimb    
    }

    lesson 6: Lesson {
        learn to largeclimb     
    }
}